In [29]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [30]:
iris = load_iris()
df = pd.DataFrame(data = iris["data"], columns=iris["feature_names"])
df["target"] = iris["target"]
tgt = "target"
ls_features = [x for x in df.columns if x not in [tgt]]

In [31]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [32]:
df['target'].value_counts(1)

2    0.333333
1    0.333333
0    0.333333
Name: target, dtype: float64

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X = df[ls_features]
y = df[tgt]

In [35]:
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=5)

In [36]:
from sklearn.naive_bayes import GaussianNB

In [37]:
model=GaussianNB()

In [38]:
model.fit(X_train, y_train)

GaussianNB()

In [39]:
from sklearn.metrics import roc_auc_score,accuracy_score,confusion_matrix,f1_score

def metricas(model,Xv,yv): #Mide efectividad de un Modelo Predictivo
    print( " Acc Validate: %.3f" %accuracy_score(y_pred=model.predict(Xv),y_true=yv))
    print( " Matrix Conf Validate: ", "\n",confusion_matrix(y_pred=model.predict(Xv),y_true=yv))

In [40]:
metricas(model, X_train,y_train)

 Acc Validate: 0.973
 Matrix Conf Validate:  
 [[38  0  0]
 [ 0 35  1]
 [ 0  2 36]]


In [41]:
metricas(model, X_test,y_test)

 Acc Validate: 0.921
 Matrix Conf Validate:  
 [[12  0  0]
 [ 0 13  1]
 [ 0  2 10]]


In [42]:
f1_score( y_test,model.predict(X_test),average='weighted')

0.9206975459638602

## Ejemplo 2

In [43]:
dataset = pd.read_csv('../data/Social_Network_Ads.csv')
X_ = dataset.iloc[:, [2, 3]]
y_ = dataset.iloc[:, -1]

In [44]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [45]:

from sklearn.model_selection import train_test_split
X_train_, X_test_, y_train_, y_test_ = train_test_split(X_, y_, test_size = 0.25, random_state = 0)

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_ = sc.fit_transform(X_train_)
X_test_ = sc.transform(X_test_)

In [47]:
classifier = GaussianNB()
classifier.fit(X_train_, y_train_)

GaussianNB()

In [48]:

print(classifier.predict(sc.transform([[30,87000]])))

[0]


In [49]:

y_pred_ = classifier.predict(X_test_)

In [50]:

cm = confusion_matrix(y_train_, y_train_)
print(cm)
accuracy_score(y_train_, y_train_)

[[189   0]
 [  0 111]]


1.0

In [51]:

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test_, y_pred_)
print(cm)
accuracy_score(y_test_, y_pred_)

[[65  3]
 [ 7 25]]


0.9